/**
 * Burmese (my-MM) translations. Keys mirror `labels.en`. This is the production
 * language. Any key omitted here falls back to the English string (see `labels.ts`),
 * so new strings can be translated manually over time without breaking the app.
 */
import type { DeepPartial, Labels } from "./labels.en";

export const my: DeepPartial<Labels> = {
  common: {
    appName: "LGY",
    save: "သိမ်းမယ်",
    saving: "သိမ်းနေပါသည်...",
    cancel: "မလုပ်တော့ပါ",
    back: "နောက်ပြန်",
    next: "ရှေ့ဆက်",
    confirm: "အတည်ပြု",
    yes: "ဟုတ်ကဲ့",
    no: "မဟုတ်ပါ",
    delete: "ဖျက်မယ်",
    edit: "ပြင်မယ်",
    add: "ထပ်ထည့်မယ်",
    addNew: "အသစ်ထည့်မယ်",
    search: "ရှာမယ်",
    loading: "ခဏစောင့်ပါ...",
    today: "ဒီနေ့",
    total: "စုစုပေါင်း",
    noData: "အချက်အလက်မရှိသေးပါ",
    photo: "ဓာတ်ပုံ",
    saved: "သိမ်းပြီးပါပြီ",
    done: "ပြီးပြီ",
    undo: "ပြန်ဖျက်မယ်",
    finish: "ပြီးဆုံး",
    optional: "လိုရင်ဖြည့်ပါ",
  },

  units: {
    htee: "ထည်",
    kyat: "ကျပ်",
  },

  auth: {
    login: "ဝင်မယ်",
    logout: "ထွက်မယ်",
    logoutConfirmTitle: "အကောင့်မှ ထွက်ရန်သေချာလား?",
    logoutConfirmYes: "ဟုတ်၊ ထွက်မယ်",
    username: "အသုံးပြုသူအမည်",
    password: "စကားဝှက်",
    loginTitle: "အကောင့်ဝင်ရန်",
    loginFailed: "အသုံးပြုသူအမည် (သို့) စကားဝှက် မှားနေပါသည်။",
    sessionExpired: "ပြန်ဝင်ရန်လိုအပ်သည်။",
    roleAdmin: "Admin",
    roleStaff: "ဆိုင်စတပ်",
    roleManager: "Manager",
  },

  nav: {
    staff: "ဆိုင်စတပ်",
    admin: "Admin",
  },

  staff: {
    home: "LGY ဆိုင်",
    sell: "အရောင်း",
    receive: "ငွေလက်ခံ",
    debts: "အကြွေးစာရင်း",
    transfer: "ဆိုင်ပို့",
    viewStock: "ဆိုင်အထည်စာရင်း",
    close: "ဆိုင်သိမ်း",
  },

  sell: {
    title: "ပစ္စည်းရောင်းရန်",
    pickCustomer: "ဖောက်သည်ရွေးပါ",
    changeCustomer: "ဖောက်သည်ပြောင်းရန်",
    pickItem: "ဘာရောင်းမလဲ?",
    chooseQty: "အထည်",
    choosePrice: "စျေးနှုန်း",
    cartEmpty: "ပစ္စည်းတစ်ခုမှ မထည့်ရသေးပါ",
    cartHas: "ထည့်ထားသော",
    addAnother: "နောက်တစ်ခုထပ်ထည့်",
    review: "စစ်ဆေးမယ်",
    paidNow: "ယခုရရှိငွေ",
    grandTotal: "စုစုပေါင်းငွေ",
    remaining: "ကျန်ငွေ",
    submit: "ရောင်းမယ်",
    success: "အရောင်းသိမ်းပြီးပါပြီ",
    voicePiecesSold: (n: number, label: string) => `${label} ${n} ထည် ရောင်းပြီးပါပြီ`,
    inStock: "လက်ကျန်",
    notEnough: "လက်ကျန် မလုံလောက်ပါ",
    noItems: "ပစ္စည်းတစ်ခုမှ မထည့်ရသေးပါ",
    noCustomer: "ဖောက်သည်ကို အရင်ရွေးပါ",
    cantPayMore: "ပေးငွေက စုစုပေါင်းငွေထက်များနေသည်",
    searchCustomer: "ဖောက်သည်ရှာရန်...",
    noResults: "ရှာဖွေမှုနှင့်ကိုက်ညီသော အချက်အလက်မရှိပါ",
    line: "လိုင်း",
    removeLine: "ဖျက်မယ်",
    currentDebt: "ယခုအကြွေးကျန်",
    typeChoose: "အရောင်းအမျိုးအစား",
    wholesale: "လက်ကား",
    retail: "လက်လီ",
    notes: "မှတ်ချက်",
    asCredit: "အကြွေး",
    oversellNote: "လက်ကျန်ထက် ပိုရောင်းနေသည် — ရောင်းနိုင်ပါသည်။ မှတ်တမ်းတင်ပြီး နောက်မှ ပြန်ညှိနိုင်သည်။",
    walkIn: "အမည်မလို — လမ်းသွားရောင်း",
    walkInCustomer: "Walk in",
    walkInPaidFull: "ငွေအပြည့် လက်ခံပြီး (လက်ငင်းရောင်း)",
    whoBuyer: "ဘယ်သူ့ကို ရောင်းမလဲ?",
    existingBuyer: "ဖောက်သည် အဟောင်း",
    newBuyer: "ဖောက်သည် အသစ်",
    buyerName: "ဝယ်သူ အမည်",
    buyerNamePlaceholder: "နာမည် ရိုက်ထည့်ပါ",
    saveBuyer: "သိမ်းထားမယ် (နောက်ထပ် ရောင်းရန်)",
    oneTimeBuyer: "နာမည်မထည့်ပါ",
    manualItem: "ကိုယ်တိုင် ရိုက်ထည့်",
    itemName: "ပစ္စည်း အမည်",
    itemNamePlaceholder: "ပစ္စည်းအမည် ရိုက်ထည့်ပါ",
    itemNameRequired: "ပစ္စည်းအမည် ဖြည့်ပါ",
    freeNotePlaceholder: "မှတ်ချက်",
    noteRequired: "ဈေး 0 ဖြစ်ပါက မှတ်ချက် ဖြည့်ရန် လိုအပ်သည်",
    savePrint: "သိမ်း + ပုံနှိပ်",
  },

  receive: {
    title: "ငွေလက်ခံမယ်",
    chooseCustomer: "ဖောက်သည်ရွေးပါ",
    amount: "လက်ခံသည့် ငွေပမာဏ",
    success: "ငွေလက်ခံပြီးပါပြီ",
    voiceReceived: (amount: string) => `${amount} ကျပ် လက်ခံပြီးပါပြီ`,
    notes: "မှတ်ချက်",
    payAll: "အကုန်",
  },

  debts: {
    title: "အကြွေးစာရင်း",
    none: "အကြွေးကျန်ရှိသူ မရှိပါ",
    clickToReceive: "ငွေလက်ခံရန် နှိပ်ပါ",
  },

  transfer: {
    title: "ဆိုင်သို့ ပစ္စည်းပို့",
    fromLocation: "မှ",
    toLocation: "သို့",
    addItem: "ပစ္စည်းထပ်ထည့်",
    success: "ပစ္စည်းပို့ပြီးပါပြီ",
    notes: "မှတ်ချက်",
    locWarehouse: "ဂိုဒေါင်",
    locShop: "ဆိုင်",
    locInTransit: "ကားပေါ်",
    notEnough: "ပို့မယ့်နေရာတွင် လက်ကျန် မလုံလောက်ပါ",
    history: "ဆိုင်ပို့ မှတ်တမ်း",
    slipTitle: "ပစ္စည်းပို့ စလစ်",
    totalPieces: "စုစုပေါင်း",
    savePrint: "သိမ်း & ပုံနှိပ်",
    empty: "ပို့ဆောင်မှု မရှိသေးပါ",
    deliveryBy: "ပို့ဆောင်မှု (လိုရင်)",
    driver: "ကားသမား",
    driverFee: "ကားခ",
    otherDriver: "အခြား / တက္ကစီ",
    noDriver: "— မရှိ —",
  },

  close: {
    title: "နေ့စဉ်ငွေတွက်",
    today: "ဒီနေ့",
    openingCash: "ပွင့်ငွေ (မနေ့က ပိတ်ငွေ)",
    received: "ဒီနေ့ ရငွေ",
    paidOut: "ဒီနေ့ ပေးငွေ",
    expectedCash: "ရှိရမည့် ငွေ",
    countedCash: "ရေတွက်တွေ့ရှိ ငွေ",
    difference: "ခြားနားချက်",
    differenceShortfall: "လိုငွေ",
    differenceSurplus: "ပိုငွေ",
    keepForTomorrow: "မနက်ဖြန်အတွက် ချန်ထား",
    takeHome: "အိမ်ယူသွား",
    save: "ပိတ်မယ်",
    success: "နေ့ပိတ်သိမ်းပြီးပါပြီ",
    alreadyClosed: "ဒီနေ့ ပိတ်ပြီးသား ဖြစ်နေပါပြီ",
    history: "မှတ်တမ်း",
  },

  history: {
    title: "အရောင်းမှတ်တမ်း",
    empty: "အရောင်းမှတ်တမ်း မရှိသေးပါ",
    reprint: "ပြန်ပုံနှိပ်",
  },

  returns: {
    action: "ပစ္စည်း/ငွေ ပြန်အမ်း",
    title: "ပစ္စည်း ပြန်အမ်းရန်",
    refund: "ပြန်အမ်းငွေ",
    submit: "ပြန်အမ်း မှတ်မယ်",
    existing: "ပြန်အမ်းမှု",
    reason: "အကြောင်းပြချက်",
    void: "ပယ်ဖျက်",
  },

  expenses: {
    title: "ကုန်ကျစရိတ်",
    add: "ကုန်ကျစရိတ် ထည့်မယ်",
    category: "အမျိုးအစား",
    amount: "ပမာဏ (ကျပ်)",
    date: "ရက်စွဲ",
    recipient: "ပေးသူ",
    paidToNone: "—",
    paidToEmployee: "ဝန်ထမ်း",
    paidToDriver: "ကားသမား",
    paidToOther: "အခြား (နာမည်ရိုက်ပါ)",
    notes: "မှတ်ချက်",
    empty: "ကုန်ကျစရိတ် မရှိသေးပါ",
    void: "ပယ်ဖျက်",
    total: "စုစုပေါင်း (ပြထား)",
    paySalary: "လစာပေးမယ်",
    pay: "ပေးမယ်",
  },

  tailorWork: {
    inHand: "ချုပ်ဆရာထံ",
    nothing: "ချုပ်ဆရာထံ ပစ္စည်းမရှိ",
    send: "ချုပ်ရန် ပို့မယ်",
    receive: "ပြန်လက်ခံမယ်",
    qty: "အရေအတွက်",
    addItem: "ပစ္စည်းထည့်",
    inputItem: "ပို့ထားသည်",
    sentQty: "ပို့",
    outputItem: "ပြန်ရ",
    receivedQty: "ရရှိ",
    loss: "လျော့",
    fee: "ချုပ်ခ (ကျပ်)",
    addLine: "လိုင်းထည့်",
    receivedTooMany: "ရရှိသည် ပို့သည်ထက် မများရ",
    history: "ချုပ်လုပ်ငန်း မှတ်တမ်း",
    sendSlip: "ချုပ်ရန် ပို့",
    receiveSlip: "ပြန်လက်ခံ",
    savePrint: "သိမ်း & ပုံနှိပ်",
  },

  tailorLedger: {
    charges: "ပေးရန် ချုပ်ခ",
    payments: "ပေးငွေများ",
    addCharge: "ချုပ်ခ ထည့်မယ်",
    addPayment: "ငွေပေး မှတ်မယ်",
    amount: "ပမာဏ (ကျပ်)",
    pieces: "အရေအတွက်",
    feePerPiece: "တစ်ထည် ချုပ်ခ (ကျပ်)",
    note: "မှတ်ချက်",
    method: "နည်းလမ်း",
    owe: "ပေးရန်",
    credit: "ကြိုတင်ပေး / အကြွေး",
    settled: "ရှင်းပြီး",
    noCharges: "ချုပ်ခ မရှိသေးပါ",
    noPayments: "ငွေပေး မရှိသေးပါ",
    void: "ပယ်ဖျက်",
    useFee: "အရေအတွက် × ချုပ်ခ သုံးမယ်",
    methodCash: "ငွေသား",
    methodBank: "ဘဏ်",
    methodMobile: "မိုဘိုင်း",
    methodOther: "အခြား",
  },

  filter: {
    today: "ဒီနေ့",
    week: "ဒီအပတ်",
    month: "ဒီလ",
    all: "အားလုံး",
  },

  customerDetail: {
    activity: "ဝယ်ယူ/ပေးချေမှု",
    bought: "ဝယ်ထား (အကြွေး)",
    paid: "ပေးပြီး",
    recentSales: "လတ်တလော အရောင်း",
    recentPayments: "လတ်တလော ပေးငွေ",
    noSales: "အရောင်း မရှိသေးပါ",
    noPayments: "ပေးငွေ မရှိသေးပါ",
    topDebtors: "အကြွေး အများဆုံး",
  },

  shop: {
    main: "ပင်မဆိုင်",
    test: "စမ်းသပ်ဆိုင်",
    testTag: "စမ်းသပ်",
    switchToTest: "စမ်းသပ်ဆိုင်သို့ ပြောင်းမယ်",
    backToMain: "ပင်မဆိုင်သို့ ပြန်သွားမယ်",
    bannerTitle: "စမ်းသပ်ဆိုင်",
    bannerNote: "လေ့ကျင့်ရန်အတွက်သာ — ဤနေရာတွင် ပြုလုပ်သမျှသည် အစစ်အမှန် ရောင်းအား၊ ပစ္စည်း၊ ငွေကို မထိခိုက်ပါ။",
  },

  settings: {
    title: "ဆိုင် & ဘောက်ချာ",
    help: "ဤအချက်အလက်များသည် ပုံနှိပ်ဘောက်ချာတွင် ပေါ်ပါမည်။ ကွက်လပ်ထားလျှင် မူရင်းအတိုင်း သုံးပါမည်။",
    shopName: "ဆိုင်အမည်",
    address: "လိပ်စာ",
    phone: "ဖုန်း",
    social: "ဆိုရှယ်မီဒီယာ",
    socialPlaceholder: "Facebook / Viber / Telegram",
    receiptHeader: "ဘောက်ချာ ခေါင်းစဉ်ခွဲ",
    receiptFooter: "အောက်ခြေ / ကျေးဇူးတင်စကား",
    preview: "ဘောက်ချာ နမူနာ",
    saved: "သိမ်းပြီးပါပြီ",
  },

  admin: {
    home: "Admin",
    dashboard: "ခြုံငုံကြည့်ရှု",
    navGroups: {
      people: "လူများ",
      stock: "ပစ္စည်း & လက်ကျန်",
      money: "ငွေကြေး",
      system: "စနစ်",
    },
    itemTypes: "ပစ္စည်းအမျိုးအစားများ",
    customers: "ဖောက်သည်များ",
    suppliers: "ပစ္စည်းရှင်များ",
    tailors: "ချုပ်သမားများ",
    drivers: "ကားသမားများ",
    employees: "ဝန်ထမ်းများ",
    inventory: "လက်ကျန်စာရင်း",
    openingStock: "အစစတော့ထည့်",
    transfers: "ပစ္စည်းပို့စာရင်း",
    supplierOrders: "အလိပ်မှာစာရင်း",
    closes: "နေ့ပိတ်စာရင်း",
    sales: "အရောင်းစာရင်း",
    stockCount: "စတော့ရေတွက်",
    exceptions: "လက်ကျန်မကိုက်မှု",
    expenses: "ကုန်ကျစရိတ်",
    settings: "ဆက်တင်များ",
    users: "အသုံးပြုသူများ",
    userMgmt: {
      title: "အကောင့်များ",
      add: "အသုံးပြုသူ ထည့်မယ်",
      username: "အသုံးပြုသူအမည်",
      displayName: "နာမည်",
      role: "ရာထူး",
      roleAdmin: "အက်ဒမင်",
      roleStaff: "ဝန်ထမ်း",
      password: "စကားဝှက်",
      passwordHint: "အနည်းဆုံး ၄ လုံး",
      resetPassword: "စကားဝှက် ပြန်သတ်မှတ်",
      newPassword: "စကားဝှက်အသစ်",
      enable: "ဖွင့်မယ်",
      disable: "ပိတ်မယ်",
      active: "ဖွင့်ထား",
      disabled: "ပိတ်ထား",
      you: "သင်",
      confirmDisable: "ဒီအကောင့်ကို ပိတ်မလား။ ဝင်လို့ရတော့မှာ မဟုတ်ပါ။",
    },
    saved: "သိမ်းပြီးပါပြီ",
    activeOnly: "သုံးနေသူများသာ",
    showInactive: "ရပ်ထားသူများ ပြပါ",
    inactive: "ရပ်ထား",
    feePerTrip: "တစ်ခေါက်",
    monthly: "လစဉ်",
    feePerPiece: "တစ်ထည်ခ",
    toPay: "ပေးရန်",
    openingStockHistory: "အစတော့ မှတ်တမ်း",
    atLeastOneQty: "အရေအတွက်အနည်းဆုံး တစ်ခု ဖြည့်ပါ",
    fields: {
      name: "အမည်",
      contact: "ဆက်သွယ်ရန်",
      photoUrl: "ဓာတ်ပုံ URL",
      notes: "မှတ်ချက်",
      status: "အခြေအနေ",
      defaultKind: "မူရင်းအရောင်းအမျိုးအစား",
      defaultFeePerPiece: "တစ်ထည်ချင်းခ (ကျပ်)",
      defaultFee: "တစ်ခေါက်ခ (ကျပ်)",
      monthlySalary: "လစဉ်လစာ (ကျပ်)",
      itemTypeKey: "ကုဒ် (UPPER_SNAKE)",
      itemTypeLabel: "မြန်မာအမည်",
      itemTypeEmoji: "ပုံ (emoji)",
      itemTypeSortOrder: "အစီအစဉ်",
      itemTypeIsActive: "သုံးနေသည်",
      itemTypeSellable: "ဆိုင်တွင် ရောင်းနိုင်",
      qty: "အရေအတွက်",
      unitCost: "တစ်ထည်ဈေး (ဝယ်ဈေး)",
      location: "နေရာ",
    },
    actions: {
      active: "သုံးနေသည်",
      inactive: "ရပ်ထား",
    },
    empty: {
      itemTypes: "ပစ္စည်းအမျိုးအစား မရှိသေးပါ",
      customers: "ဖောက်သည်တစ်ယောက်မှ မရှိသေးပါ",
      suppliers: "ပစ္စည်းရှင်တစ်ယောက်မှ မရှိသေးပါ",
      tailors: "ချုပ်သမားတစ်ယောက်မှ မရှိသေးပါ",
      drivers: "ကားသမားတစ်ယောက်မှ မရှိသေးပါ",
      employees: "ဝန်ထမ်းတစ်ယောက်မှ မရှိသေးပါ",
      transfers: "ပစ္စည်းပို့မှု မရှိသေးပါ",
      closes: "နေ့ပိတ်မှတ်တမ်း မရှိသေးပါ",
      supplierOrders: "မှာထားသော အလိပ်/ပစ္စည်း မရှိသေးပါ",
    },
    openingStockHelp:
      "စတော့လက်ကျန်စာရင်း အစသိမ်းရန်။ ဂိုဒေါင် (သို့) ဆိုင်တွင် လက်ကျန်ရှိသမျှကို ဤနေရာတွင် တစ်ကြိမ်တည်း ထည့်နိုင်သည်။",

    order: {
      pending: "မှာထားဆဲ",
      partialReceived: "တစ်ပိုင်းရောက်",
      received: "ရောက်ပြီး",
      cancelled: "ပယ်ဖျက်",
      expectedQty: "မှာထားသော အရေအတွက်",
      receivedQty: "ရောက်ပြီး",
      remainingQty: "ကျန်",
      expectedUnitPrice: "တစ်ထည်ဈေး",
      totalExpected: "စုစုပေါင်း ထင်ထားသော",
      paid: "ပေးပြီး",
      remaining: "ပေးရန်ကျန်",
      cancel: "ပယ်ဖျက်မယ်",
      reopen: "ပြန်ဖွင့်မယ်",
      recordPayment: "ငွေသွင်းမယ်",
      recordReceipt: "ရောက်ပြီ မှတ်မယ်",
      transportCost: "သယ်ခ",
      paymentMethod: "ငွေပေးဆောင်နည်း",
      paymentAmount: "ငွေပမာဏ",
      overpaid: "ကျော်ပေး",
      price: "ဈေး (ကျပ်)",
      transportShort: "သယ်ခ",
      totalHint: "တစ်ခုချင်းမတွက်ဘဲ စုစုပေါင်းပိုက်ဆံ",
      cancelReceipt: "ဒီပစ္စည်းရောက်မှု ပယ်ဖျက်",
      cancelReceiptConfirm: "ဒီပစ္စည်းရောက်မှု ပယ်ဖျက်မလား။ ထည့်ထားတဲ့ ပစ္စည်းကို ပြန်နုတ်ပါမယ်။",
      cancelPayment: "ဒီငွေပေးချေမှု ပယ်ဖျက်",
      cancelPaymentConfirm: "ဒီငွေပေးချေမှု ပယ်ဖျက်မလား။",
    },
  },

  exceptions: {
    title: "လက်ကျန် မကိုက်ညီမှုများ",
    help:
      "ဆိုင်တွင် စာရင်းလက်ကျန်ထက် ပိုရောင်းခဲ့သော ပစ္စည်းများ။ စာရင်းနှင့် လက်တွေ့ မကိုက်သေးပါ — လက်တွေ့ရေတွက်ပြီး ပြန်ညှိပါ။",
    none: "မကိုက်ညီမှု မရှိပါ 👍",
    systemStock: "စာရင်းအရ လက်ကျန်",
    soldBeyond: "ပိုရောင်းခဲ့",
    lastSeen: "နောက်ဆုံးတွေ့",
    contributingSales: "သက်ဆိုင်သော အရောင်းများ",
    resolve: "ပြန်ညှိမယ်",
    countedQty: "လက်တွေ့ ရေတွက်ရရှိ အရေအတွက်",
    countedQtyHint: "မဖြည့်ပါက ပစ္စည်းကိုသာ ပိတ်မည် (စာရင်းမပြင်ပါ)",
    reason: "အကြောင်းပြချက်",
    resolveSubmit: "ညှိပြီး ပိတ်မယ်",
    voided: "ပယ်ဖျက်ထား",
  },

  stockCount: {
    title: "စတော့ ရေတွက် / ပြန်ညှိ",
    help:
      "နေရာတစ်ခုရှိ လက်တွေ့လက်ကျန်ကို ရေတွက်ပြီး စာရင်းနှင့် ပြန်ညှိရန်။ ကွာသွားသည့် ပစ္စည်းများကိုသာ ပြင်ပါ။",
    location: "နေရာ",
    systemQty: "စာရင်း",
    countedQty: "ရေတွက်ရရှိ",
    reason: "အကြောင်းပြချက်",
    submit: "ပြန်ညှိမယ်",
    success: "စတော့ ပြန်ညှိပြီးပါပြီ",
    noChange: "ကွာခြားမှု မရှိပါ",
    empty: "ပစ္စည်းအမျိုးအစား မရှိသေးပါ",
  },

  salesAdmin: {
    title: "အရောင်းစာရင်း",
    empty: "အရောင်းမှတ်တမ်း မရှိသေးပါ",
    filterAll: "အားလုံး",
    payments: "ပေးငွေမှတ်တမ်း",
    noPayments: "ပေးငွေ မရှိသေးပါ",
    voidSale: "အရောင်း ပယ်ဖျက်",
    voidSaleConfirm: "ဤအရောင်းကို ပယ်ဖျက်မလား? သက်ဆိုင်ရာ ပေးငွေများကိုပါ ပြန်ရုပ်သိမ်းမည်။",
    voidPayment: "ပေးငွေ ပယ်ဖျက်",
    voided: "ပယ်ဖျက်ပြီး",
    reason: "အကြောင်းပြချက်",
    confirm: "ပယ်ဖျက်မယ်",
    walkIn: "လမ်းသွား",
  },

  domain: {
    sale: "အရောင်း",
    purchase: "အဝယ်",
    customer: "Customer name",
    supplier: "ပစ္စည်းရှင်",
    tailor: "ချုပ်သမား",
    employee: "ဝန်ထမ်း",
    driver: "ကားသမား",
    itemType: "ပစ္စည်းအမျိုးအစား",
    quantity: "အရေအတွက်",
    unitPrice: "တစ်ထည်ဈေး",
    grandTotal: "စုစုပေါင်းငွေ",
    paid: "ပေးပြီး",
    remaining: "ပေးရန်ကျန်",
    debt: "အကြွေး",
    discount: "လျှော့ဈေး",
    note: "မှတ်ချက်",
    statusUnpaid: "ငွေမရသေး",
    statusPartial: "တစ်ပိုင်းရ",
    statusPaid: "ငွေရပြီး",
    wholesale: "လက်ကား",
    retail: "လက်လီ",
  },

  receipt: {
    shopName: "LGY",
    title: "ပြေစာ",
    no: "နံပါတ်",
    customer: "ဖောက်သည်",
    item: "ပစ္စည်း",
    qty: "အထည်",
    price: "ဈေး",
    amount: "ကျသင့်",
    total: "စုစုပေါင်း",
    paid: "ပေးပြီး",
    remaining: "ကျန်ငွေ",
    thanks: "ကျေးဇူးတင်ပါသည်",
  },

  rollOrders: {
    title: "အလိပ်မှာယူမှု",
    open: "မှာထားဆဲ",
    rolls: "မှာထားသော အလိပ်",
    received: "ရောက်ပြီး",
    committedToPay: "ပေးရန်ကျန် (စုစုပေါင်း)",
    dueNow: "ယခုပေးရန် (ရောက်ပြီး)",
  },

  errors: {
    required: "ဖြည့်ရန်လိုသည်",
    networkError: "ချိတ်ဆက်မှု အဆင်မပြေပါ။ နောက်တစ်ခါပြန်ကြိုးစားပါ။",
    unknown: "တစ်ခုခု မှားနေပါသည်။",
  },
};
