/**
 * English UI strings — the SOURCE OF TRUTH and the development language.
 * Burmese translations live in `labels.my.ts` (same keys); the active dictionary
 * is chosen by NEXT_PUBLIC_LOCALE in `labels.ts`. Add new strings here first.
 */
export const en = {
  common: {
    appName: "LGY",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    back: "Back",
    next: "Next",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    addNew: "Add new",
    search: "Search",
    loading: "Loading...",
    today: "Today",
    total: "Total",
    noData: "No data yet",
    photo: "Photo",
    saved: "Saved",
    done: "Done",
    undo: "Undo",
    finish: "Finish",
    optional: "Optional",
  },

  units: {
    htee: "pcs",
    kyat: "Ks",
  },

  auth: {
    login: "Log in",
    logout: "Log out",
    logoutConfirmTitle: "Log out of your account?",
    logoutConfirmYes: "Yes, log out",
    username: "Username",
    password: "Password",
    loginTitle: "Sign in",
    loginFailed: "Wrong username or password.",
    sessionExpired: "Please sign in again.",
    roleAdmin: "Admin",
    roleStaff: "Shop staff",
    roleManager: "Manager",
  },

  nav: {
    staff: "Shop staff",
    admin: "Admin",
  },

  staff: {
    home: "LGY Shop",
    sell: "Sell",
    receive: "Receive money",
    debts: "Debts",
    transfer: "Send to shop",
    viewStock: "Shop stock",
    close: "Daily close",
  },

  sell: {
    title: "Sell items",
    pickCustomer: "Choose customer",
    changeCustomer: "Change customer",
    pickItem: "What to sell?",
    chooseQty: "Pieces",
    choosePrice: "Price",
    cartEmpty: "No items added yet",
    cartHas: "Added",
    addAnother: "Add another",
    review: "Review",
    paidNow: "Paid now",
    grandTotal: "Grand total",
    remaining: "Remaining",
    submit: "Sell",
    success: "Sale saved",
    voicePiecesSold: (n: number, label: string) => `Sold ${n} ${label}`,
    inStock: "In stock",
    notEnough: "Not enough stock",
    noItems: "No items added yet",
    noCustomer: "Choose a buyer first",
    cantPayMore: "Paid amount exceeds the total",
    searchCustomer: "Search customer...",
    noResults: "No matching results",
    line: "Line",
    removeLine: "Remove",
    currentDebt: "Current debt",
    typeChoose: "Sale type",
    wholesale: "Wholesale",
    retail: "Retail",
    notes: "Notes",
    asCredit: "On credit",
    oversellNote: "Selling beyond stock — allowed. It is logged and reconciled later.",
    walkIn: "No name — walk-in sale",
    walkInCustomer: "Walk in",
    walkInPaidFull: "Paid in full (cash sale)",
    whoBuyer: "Who are you selling to?",
    existingBuyer: "Existing customer",
    newBuyer: "New customer",
    buyerName: "Buyer name",
    buyerNamePlaceholder: "Type the name",
    saveBuyer: "Save for later (to sell again)",
    oneTimeBuyer: "One time (cash sale)",
    manualItem: "Type manually",
    itemName: "Item name",
    itemNamePlaceholder: "Type the item name",
    itemNameRequired: "Enter an item name",
    freeNotePlaceholder: "Note",
    noteRequired: "A note is required when the price is 0",
    savePrint: "Save & Print",
  },

  receive: {
    title: "Receive money",
    chooseCustomer: "Choose customer",
    amount: "Amount received",
    success: "Payment received",
    voiceReceived: (amount: string) => `Received ${amount} kyat`,
    notes: "Notes",
    payAll: "All",
  },

  debts: {
    title: "Debts",
    none: "No one owes money",
    clickToReceive: "Tap to receive money",
  },

  transfer: {
    title: "Send to shop",
    fromLocation: "From",
    toLocation: "To",
    addItem: "Add item",
    success: "Items sent",
    notes: "Notes",
    locWarehouse: "Warehouse",
    locShop: "Shop",
    locInTransit: "In transit",
    notEnough: "Not enough stock at the source",
    history: "Transfer history",
    slipTitle: "Transfer note",
    totalPieces: "Total pieces",
    savePrint: "Save & Print",
    empty: "No transfers yet",
    deliveryBy: "Delivery (optional)",
    driver: "Driver",
    driverFee: "Fee",
    otherDriver: "Other / taxi",
    noDriver: "— none —",
  },

  close: {
    title: "Daily close",
    today: "Today",
    openingCash: "Opening cash (yesterday's close)",
    received: "Received today",
    paidOut: "Paid out today",
    expectedCash: "Expected cash",
    countedCash: "Counted cash",
    difference: "Difference",
    differenceShortfall: "Shortfall",
    differenceSurplus: "Surplus",
    keepForTomorrow: "Keep for tomorrow",
    takeHome: "Take home",
    save: "Close",
    success: "Day closed",
    alreadyClosed: "Today is already closed",
    history: "History",
  },

  history: {
    title: "Sales history",
    empty: "No sales yet",
    reprint: "Reprint",
  },

  returns: {
    action: "Return / Refund",
    title: "Return items",
    refund: "Refund (cash back)",
    submit: "Record return",
    existing: "Returns",
    reason: "Reason / note",
    void: "Cancel",
  },

  expenses: {
    title: "Expenses",
    add: "Add expense",
    category: "Category",
    amount: "Amount (Ks)",
    date: "Date",
    recipient: "Paid to",
    paidToNone: "—",
    paidToEmployee: "Employee",
    paidToDriver: "Driver",
    paidToOther: "Other (type a name)",
    notes: "Notes",
    empty: "No expenses yet",
    void: "Cancel",
    total: "Total (shown)",
    paySalary: "Pay salary",
    pay: "Pay",
  },

  tailorWork: {
    inHand: "In their hands",
    nothing: "Nothing with the tailor",
    send: "Send to tailor",
    receive: "Receive from tailor",
    qty: "Qty",
    addItem: "Add item",
    inputItem: "Sent item",
    sentQty: "Sent",
    outputItem: "Got back",
    receivedQty: "Received",
    loss: "Loss",
    fee: "Sewing fee (Ks)",
    addLine: "Add line",
    receivedTooMany: "Received can't exceed sent",
    history: "Tailoring history",
    sendSlip: "Send to tailor",
    receiveSlip: "Receive from tailor",
    savePrint: "Save & Print",
  },

  tailorLedger: {
    charges: "Fees owed",
    payments: "Payments",
    addCharge: "Add fee",
    addPayment: "Add payment",
    amount: "Amount (Ks)",
    pieces: "Pieces",
    feePerPiece: "Fee per piece (Ks)",
    note: "Note",
    method: "Method",
    owe: "We owe",
    credit: "Credit / advance",
    settled: "Settled up",
    noCharges: "No fees recorded yet",
    noPayments: "No payments yet",
    void: "Cancel",
    useFee: "Use pieces × fee",
    methodCash: "Cash",
    methodBank: "Bank",
    methodMobile: "Mobile",
    methodOther: "Other",
  },

  filter: {
    today: "Today",
    week: "This week",
    month: "This month",
    all: "All",
  },

  customerDetail: {
    activity: "Activity",
    bought: "Bought (on credit)",
    paid: "Paid",
    recentSales: "Recent sales",
    recentPayments: "Recent payments",
    noSales: "No sales yet",
    noPayments: "No payments yet",
    topDebtors: "Who owes most",
  },

  shop: {
    main: "Main shop",
    test: "Test shop",
    testTag: "TEST",
    switchToTest: "Switch to Test shop",
    backToMain: "Back to Main shop",
    bannerTitle: "TEST SHOP",
    bannerNote: "Practice mode — nothing here affects real sales, stock, or money.",
  },

  settings: {
    title: "Shop & receipt",
    help: "These appear on the printed receipt. Leave a field blank to use the default.",
    shopName: "Shop name",
    address: "Address",
    phone: "Phone",
    social: "Social media",
    socialPlaceholder: "Facebook / Viber / Telegram",
    receiptHeader: "Receipt subtitle",
    receiptFooter: "Footer / thank-you",
    preview: "Receipt preview",
    saved: "Settings saved",
  },

  admin: {
    home: "Admin",
    dashboard: "Dashboard",
    navGroups: {
      people: "People",
      stock: "Catalog & stock",
      money: "Money",
      system: "System",
    },
    itemTypes: "Item types",
    customers: "Customers",
    suppliers: "Suppliers",
    tailors: "Tailors",
    drivers: "Drivers",
    employees: "Employees",
    inventory: "Stock",
    openingStock: "Opening stock",
    transfers: "Transfers",
    supplierOrders: "Supplier orders",
    closes: "Daily closes",
    sales: "Sales",
    stockCount: "Stock count",
    exceptions: "Stock exceptions",
    expenses: "Expenses",
    settings: "Settings",
    users: "Users",
    audit: "Audit log",
    export: "Export / Backup",
    userMgmt: {
      title: "User accounts",
      add: "Add user",
      username: "Username",
      displayName: "Name",
      role: "Role",
      roleAdmin: "Admin",
      roleStaff: "Staff",
      password: "Password",
      passwordHint: "At least 4 characters",
      resetPassword: "Reset password",
      newPassword: "New password",
      enable: "Enable",
      disable: "Disable",
      active: "Active",
      disabled: "Disabled",
      you: "You",
      confirmDisable: "Disable this account? They won't be able to log in.",
    },
    saved: "Saved",
    activeOnly: "Active only",
    showInactive: "Show inactive",
    inactive: "Inactive",
    feePerTrip: "Per trip",
    monthly: "Monthly",
    feePerPiece: "Per piece",
    toPay: "To pay",
    openingStockHistory: "Opening stock history",
    atLeastOneQty: "Enter at least one quantity",
    fields: {
      name: "Name",
      contact: "Contact",
      photoUrl: "Photo URL",
      notes: "Notes",
      status: "Status",
      defaultKind: "Default sale type",
      defaultFeePerPiece: "Fee per piece (Ks)",
      defaultFee: "Fee per trip (Ks)",
      monthlySalary: "Monthly salary (Ks)",
      itemTypeKey: "Code (UPPER_SNAKE)",
      itemTypeLabel: "Burmese name",
      itemTypeEmoji: "Emoji",
      itemTypeSortOrder: "Order",
      itemTypeIsActive: "Active",
      itemTypeSellable: "Sellable in shop",
      qty: "Quantity",
      unitCost: "Cost per piece (buy price)",
      location: "Location",
    },
    actions: {
      active: "Active",
      inactive: "Inactive",
    },
    empty: {
      itemTypes: "No item types yet",
      customers: "No customers yet",
      suppliers: "No suppliers yet",
      tailors: "No tailors yet",
      drivers: "No drivers yet",
      employees: "No employees yet",
      transfers: "No transfers yet",
      closes: "No daily closes yet",
      supplierOrders: "No supplier orders yet",
    },
    openingStockHelp:
      "Record your starting stock. Enter everything on hand at the warehouse or shop here, one time.",

    order: {
      pending: "Pending",
      partialReceived: "Partially received",
      received: "Received",
      cancelled: "Cancelled",
      expectedQty: "Ordered quantity",
      receivedQty: "Received",
      remainingQty: "Remaining",
      expectedUnitPrice: "Price per piece",
      totalExpected: "Expected total",
      paid: "Paid",
      remaining: "Remaining to pay",
      cancel: "Cancel order",
      reopen: "Reopen",
      recordPayment: "Record payment",
      recordReceipt: "Mark received",
      transportCost: "Transport cost",
      paymentMethod: "Payment method",
      paymentAmount: "Amount",
      overpaid: "Overpaid",
      price: "Price (Ks)",
      transportShort: "transport",
      totalHint: "Single agreed total, not per piece",
      cancelReceipt: "Cancel this arrival",
      cancelReceiptConfirm: "Cancel this arrival? The stock it added will be removed again.",
      cancelPayment: "Cancel this payment",
      cancelPaymentConfirm: "Cancel this payment?",
    },
  },

  exceptions: {
    title: "Stock exceptions",
    help:
      "Items sold beyond recorded shop stock — the ledger doesn't match reality yet. Count the shelf and reconcile.",
    none: "No exceptions 👍",
    systemStock: "System stock",
    soldBeyond: "Sold beyond",
    lastSeen: "Last seen",
    contributingSales: "Contributing sales",
    resolve: "Reconcile",
    countedQty: "Counted quantity",
    countedQtyHint: "Leave blank to just close it (no stock change)",
    reason: "Reason",
    resolveSubmit: "Reconcile & close",
    voided: "Cancelled",
  },

  stockCount: {
    title: "Stock count / adjust",
    help:
      "Count the physical stock at a location and reconcile the ledger to it. Only edit the items that differ.",
    location: "Location",
    systemQty: "System",
    countedQty: "Counted",
    reason: "Reason",
    submit: "Reconcile",
    success: "Stock reconciled",
    noChange: "No change",
    empty: "No item types yet",
  },

  salesAdmin: {
    title: "Sales",
    empty: "No sales yet",
    filterAll: "All",
    payments: "Payments",
    noPayments: "No payments yet",
    voidSale: "Cancel sale",
    voidSaleConfirm: "Cancel this sale? Payments recorded on it will also be reversed.",
    voidPayment: "Cancel payment",
    voided: "Cancelled",
    reason: "Reason",
    confirm: "Cancel",
    walkIn: "Walk-in",
  },

  domain: {
    sale: "Sale",
    purchase: "Purchase",
    customer: "Customer name",
    supplier: "Supplier",
    tailor: "Tailor",
    employee: "Employee",
    driver: "Driver",
    itemType: "Item type",
    quantity: "Quantity",
    unitPrice: "Price per piece",
    grandTotal: "Grand total",
    paid: "Paid",
    remaining: "Remaining to pay",
    debt: "Debt",
    discount: "Discount",
    note: "Note",
    statusUnpaid: "Unpaid",
    statusPartial: "Partial",
    statusPaid: "Paid",
    wholesale: "Wholesale",
    retail: "Retail",
  },

  receipt: {
    shopName: "LGY",
    title: "Receipt",
    no: "No",
    customer: "Customer",
    item: "Item",
    qty: "Pieces",
    price: "Price",
    amount: "Amount",
    total: "Total",
    paid: "Paid",
    remaining: "Remaining",
    thanks: "Thank you!",
  },

  rollOrders: {
    title: "Roll orders",
    open: "Open orders",
    rolls: "Rolls ordered",
    received: "received",
    committedToPay: "Committed to pay",
    dueNow: "Due now (received)",
  },

  audit: {
    title: "Audit log",
    subtitle: "Every change made in the system — newest first.",
    failuresOnly: "Failures only",
    all: "All",
    searchPlaceholder: "Search action / user / route…",
    success: "OK",
    failed: "Failed",
    noData: "No activity recorded yet.",
    shopMain: "Main",
    shopTest: "Test",
    older: "Older",
    newer: "Newer",
  },

  errors: {
    required: "Required",
    networkError: "Connection problem. Please try again.",
    unknown: "Something went wrong.",
  },
};

export type Labels = typeof en;

/**
 * Deep-partial of the dictionary so a translation file can be filled in over
 * time — any missing key falls back to English (see `labels.ts`). Function-valued
 * entries (e.g. voice messages) are kept whole rather than made partial.
 */
export type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends (...args: never[]) => unknown
    ? T[K]
    : T[K] extends object
      ? DeepPartial<T[K]>
      : T[K];
};
